### ISSUE TITLE
Enums are not translated to types

### ISSUE THREAD

**Issue by giovanni-orciuolo** [CosmWasm/ts-codegen#10]
In my JSON schema I have this:
```json
"CodeIdType": {
    "type": "string",
    "enum": [
      "Proxy",
      "Multisig",
      "Govec",
      "Staking"
    ]
}
```

`CodeIdType` is referenced in the generated TS, but the type itself is not generated. I expect to have something like:
```ts
export type CodeIdType = "Proxy" | "Multisig" | "Govec" | "Staking";
```

Just like string aliases are currently translated, for example:
```json
"Addr": {
    "type": "string"
}
```

Becomes
```ts
export type Addr = string;
```

**Comment by pyramation** [comment]
thanks! for types we're currently using `json-schema-to-typescript`

https://github.com/pyramation/cosmwasm-typescript-gen/blob/master/packages/cosmwasm-typescript-gen/src/index.ts#L8

https://github.com/pyramation/cosmwasm-typescript-gen/blob/master/packages/cosmwasm-typescript-gen/src/index.ts#L36-L41

**Comment by pyramation** [comment]
I do think we should consider writing this from scratch, for reasons such as this. I just want to mention that, this may be a PR suited for `json-schema-to-typescript`, however, I'm super open to exploring parsing types from scratch, as I've started to document here: https://github.com/pyramation/cosmwasm-typescript-gen/issues/7

**Comment by pyramation** [comment]
enums are exported correctly now https://github.com/CosmWasm/ts-codegen/blob/871479982969e89f40b75ca5c85e8bed34a824da/__output__/vectis/factory/FactoryContract.ts#L11
