### ISSUE TITLE
When query message name is the same as execute message name there are conflicts.

### ISSUE THREAD

**Issue by Rcontre360** [CosmWasm/ts-codegen#140]
When query message name is the same as execute message name there are conflicts. Example, create a contract where you have a query message and execute message with the same name. When the client is generated with this it will have typescript issues because the return values of an execution and a query are different.

**Comment by pyramation** [comment]
this is a known issue and there is a workaround, in the options you can set:

https://github.com/CosmWasm/ts-codegen/tree/main?tab=readme-ov-file#client-options

`client.execExtendsQuery` should be `false`
