### ISSUE TITLE
Allow cli generation to configure bundle behaviour

### ISSUE THREAD

**Issue by iboss-ptk** [CosmWasm/ts-codegen#52]
Currently bundle has option to specify bundle files and scope but not available to cli.

It would be helpful if we can have `--bundle-file`, `--bundle-scope`

**Comment by pyramation** [comment]
should be fixed!

```
--bundle ## or --no-bundle
--bundleFile
--bundleScope
```

- [ ] add docs for CLI

npm install -g @cosmwasm/ts-codegen@0.11.0

@iboss-ptk I'd like to mention we should encourage programmatic usage, or find a way to use the `TSBuilderOptions` somehow. The CLI is going to move towards less recommended usage.

can you checkout https://github.com/CosmWasm/ts-codegen#programmatic-usage and see if there's a way to integrate this by creating a JSON of the `TSBuilderOptions` object?

**Comment by pyramation** [comment]
also @iboss-ptk in the future, I plan to (hopefully soon) do non-scoped bundles https://github.com/CosmWasm/ts-codegen/issues/49

the reason for scoped is so it puts everything neatly in one object (makes a nice combo with telescope), but for some pure contract projects, I think this pure non-scoped bundling will be nice. Keep an eye out for that issue when it comes out, I think will be nicer ;)

**Comment by iboss-ptk** [comment]
Will check them out!
