### ISSUE TITLE
Client type

### ISSUE THREAD

**Issue by taiki1frsy** [CosmWasm/ts-codegen#57]
Currently ts-codegen use` SigningCosmWasmClient` for the client instead of `CosmWasmSigner`?
`CosmWasmSigner` is just a wrapper of `SigningCosmWasmClient` in ts-relayer.
But, I think it's more useful.

One of the reasons to prefer `CosmWasmSigner` is that it contains senderAddress to include as an argument of the many methods which `SigningCosmWasmClient` has.

**Comment by pyramation** [comment]
does it make sense to make this an option? It could make sense to do one as a default but have an option to use the `CosmWasmSigner`.

pardon my naivety, but would there be a reason that some developers would want to use `SigningCosmWasmClient` over `CosmWasmSigner `?

**Comment by taiki1frsy** [comment]
For less code? (by not making `CosmWasmSigner` over `SigningCosmWasmClient`.)
But, I don't see any productive reason to do so in the end.

**Comment by taiki1frsy** [comment]
@pyramation 
Ethan said it's better to use type from the cosmjs for `ts-codegen`.
So I retrieve this and request the revision about `SigningCosmWasmClient` in Cosmjs repo.

**Comment by pyramation** [comment]
oh, so does this mean we can close this issue and it will be updated in cosmjs? 

I think requiring a signer from cosmjs or cosmwasm feels more official than the relayer repo.

**Comment by taiki1frsy** [comment]
Yes, you can, please.

> I think requiring a signer from cosmjs or cosmwasm feels more official than the relayer repo.

I also think so. hope it will be treated well there.
