### ISSUE TITLE
Support CosmWasm 1.1 Schemas

### ISSUE THREAD

**Issue by JakeHartnell** [CosmWasm/ts-codegen#59]
Really excited for CosmWasm 1.1 schemas... would be great to get support for that so we can start using them.

**Comment by pyramation** [comment]
@uint do you have any examples I can use for testing?

**Comment by uint** [comment]
Hi, yes!

https://github.com/CosmWasm/cosmwasm/blob/main/contracts/hackatom/schema/hackatom.json
https://github.com/CosmWasm/cosmwasm/blob/main/contracts/cyberpunk/schema/cyberpunk.json

And other contracts in there. Does that work?

**Comment by pyramation** [comment]
Thanks perfect, thank you @uint !

**Comment by pyramation** [comment]
PR here https://github.com/CosmWasm/ts-codegen/pull/60
