### ISSUE TITLE
optional tuples breaks codegen

### ISSUE THREAD

**Issue by pyramation** [CosmWasm/ts-codegen#65]
schema https://gist.github.com/pyramation/f6c5cb37a13ed461fd7cbbcf7b13422b

culprit: 
```json
              "start_after": {
                "type": [
                  "array",
                  "null"
                ],
                "items": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  }
                ],
                "maxItems": 2,
                "minItems": 2
              }
```

**Comment by pyramation** [comment]
should be fixed with #66

**Comment by grod220** [comment]
Sadly, the error seems to persist after the version bump: https://github.com/grod220/ts-codegen-example

**Comment by pyramation** [comment]
I left one case out — please try now! thanks @grod220

**Comment by grod220** [comment]
Sorry, but think I found a follow up issue with the types is generates for this. It generates something like:

```typescript
import { ArrayOf_SharesResponseItem } from "./AccountNft.types";

export interface AccountNftReadOnlyInterface {
  allDebtShares: () => Promise<ArrayOfSharesResponseItem>;
}
```

This does not compile because the import has an underscore `_` in the name and the type does not.
