### ISSUE TITLE
Query enum tuple format missing argument

### ISSUE THREAD

**Issue by grod220** [CosmWasm/ts-codegen#67]
When you have a query type such as:

```rust
#[cw_serde]
#[derive(QueryResponses)]
pub enum QueryMsg {
    #[returns(String)]
    AllPreviousOwners(String),
```

The generated typescript will be missing the String argument required for this query:

```typescript
  allPreviousOwners = async (): Promise<String> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_previous_owners: {}
    });
  };
```

Reproducible example here: https://github.com/grod220/ts-codegen-example/blob/master/contracts/account-nft/src/msg/query.rs#L32-L33

**Comment by pyramation** [comment]
related (if not the same): https://github.com/CosmWasm/ts-codegen/issues/21
