### ISSUE TITLE
Generated ts client files misses override modifier

### ISSUE THREAD

**Issue by dadamu** [CosmWasm/ts-codegen#78]
The generated client file from json schema from `cw_serde` could not work properly since it misses the `override` modifier.
For instance, the generated Poap.client.ts shows:
```ts
export class PoapQueryClient implements PoapReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  methods...
}
export class PoapClient extends PoapQueryClient implements PoapInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
 
  methods...
}
```

Then, thhe error shows:
```
../types/contracts/poap/Poap.client.ts:133:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'PoapQueryClient'.

133   client: SigningCosmWasmClient;
      ~~~~~~
../types/contracts/poap/Poap.client.ts:135:3 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'PoapQueryClient'.

135   contractAddress: string;
```

After adding override modifier to PoapClient property can solve the issue, like:
```ts
export class PoapClient extends PoapQueryClient implements PoapInterface {
  override client: SigningCosmWasmClient;
  sender: string;
  override contractAddress: string;
 
  methods...
}
```

**Comment by pyramation** [comment]
hi @dadamu are do you happen to have a method of the same name in both your `ExecuteMsg` and `QueryMsg`?

**Comment by dadamu** [comment]
@pyramation No, they don't have the same name, the example contract is [here](https://github.com/desmos-labs/desmos-contracts/blob/master/contracts/poap/src/msg.rs#L39).
However `PoapClient` and `PoapQueryClient` has the same name properties, `client` and `contractAddress`. I added `override` manually then solved the issue.

**Comment by pyramation** [comment]
I will look into making an option for this.

In the meantime, it looks like you can also set `noImplicitOverride` to `false` in your `tsconfig.json`

**Comment by pyramation** [comment]
tracking here https://github.com/CosmWasm/ts-codegen/pull/79

**Comment by dadamu** [comment]
@pyramation Thanks for the help!
