### ISSUE TITLE
Mutation property type error in generated react query file

### ISSUE THREAD

**Issue by dadamu** [CosmWasm/ts-codegen#80]
The generated react query from cw721-base has the error in `useCw721BaseMintMutation` function from the `Cw721BaseMintMutation` with wrong type msg property.
The `msg` in `Cw721BaseMintMutation ` is using generated msg whose properties are in snake-case, it mismatches the client `mint` function to use the object with camel-case naming:

Here is an example:
```ts
export interface Cw721BaseMintMutation {
  client: Cw721BaseClient;
  msg: MintMsgForNullable_Empty;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useCw721BaseMintMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, Cw721BaseMintMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, Cw721BaseMintMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.mint(msg, fee, memo, funds), options);
```

The structure of msg are snake case naming:
```ts
export interface MintMsgForNullable_Empty {
  extension?: Empty | null;
  owner: string;
  token_id: string;
  token_uri?: string | null;
}
```

The client mint required args are camel case naming:
```ts
mint = async ({
    extension,
    owner,
    tokenId,
    tokenUri
  }: {
    extension?: Empty;
    owner: string;
    tokenId: string;
    tokenUri?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      mint: {
        extension,
        owner,
        token_id: tokenId,
        token_uri: tokenUri
      }
    }, fee, memo, funds);
  };
```

**Comment by pyramation** [comment]
so the client is ok, it's a mismatch between the react-query interface and implementation?

@adairrr have you experienced this? I think it could be a relatively simple fix. We may need to duplicate the interface if we're reusing it, and make a snake case version.

**Comment by dadamu** [comment]
@pyramation yes, client is ok. The error happens in react-query files.

**Comment by dadamu** [comment]
@adairrr sure, here it is https://github.com/CosmWasm/cw-nfts/tree/main/contracts/cw721-base/schema

**Comment by adairrr** [comment]
I was able to repro the issue - should be an easy fix. It's interesting to me that the `msg` uses the actual type instead of expanding it like everywhere else.

**Comment by adairrr** [comment]
For instance at the revoke mutation, it uses the pascal case as well:
```ts
export interface Test721RevokeMutation {
  client: Test721Client;
  msg: {
    spender: string;
    tokenId: string;
  };
  args?: {...};
}
```

**Comment by pyramation** [comment]
@dadamu try this

```
Successfully published:
 - @cosmwasm/ts-codegen@0.23.0
 ```

**Comment by dadamu** [comment]
@pyramation Thanks for the help, but after this changes, non-cw721 schema codegen will be error:
```
  var msgType = (0, _utils.createTypedObjectParams)(context, jsonschema).typeAnnotation;
                                                                        ^
TypeError: Cannot read properties of undefined (reading 'typeAnnotation')
    at createReactQueryMutationArgsInterface (~/node_modules/wasm-ast-types/main/react-query/react-query.js:209:73)
    at ~/node_modules/wasm-ast-types/main/react-query/react-query.js:250:13
    at Array.reduce (<anonymous>)
...
```
The whole schemas I used are [here](https://github.com/desmos-labs/contract-utils/tree/main/types), both cw721-schemas and schemas.

In addition, `StdFee` and `Coin` are not imported properly after the last changes, I guess it is because the `context.addUtil` are removed [here](https://github.com/CosmWasm/ts-codegen/commit/60b120de0e53d689a2463c276f3a37c384eea76b#diff-3f370cf7733fb1f717121e534fc3cf410c7d051ef05e2447362b4605153e9b08L416-L417).

**Comment by adairrr** [comment]
Oof @dadamu that was totally my fault, apologies. Opened a new PR with the fixed changes.
https://github.com/CosmWasm/ts-codegen/pull/86
