### ISSUE TITLE
Conflict with "no implicit override" TS rule.

### ISSUE THREAD

**Issue by j0nl1** [CosmWasm/ts-codegen#82]
In case you have this rule active in your tsconfig, you have to update manually to include override each time they are generated. Will be great to be included in the generation 😄 

![image](https://user-images.githubusercontent.com/40375118/202502537-38a131c1-6f7c-4dcb-8d08-09f396301994.png)

**Comment by pyramation** [comment]
hey @j0nl1 does this help https://github.com/CosmWasm/ts-codegen/pull/79 ?

we added a feature for [this](https://github.com/CosmWasm/ts-codegen#client-options) `client.noImplicitOverride`

**Comment by j0nl1** [comment]
amazing, absolutely, this solve my issue!
