### ISSUE TITLE
Funds naming collision

### ISSUE THREAD

**Issue by adairrr** [CosmWasm/ts-codegen#97]
If you have a parameter in a message called `funds` it collides with the `funds` that one can provide for the coins in the message. 

Example:
```rust
pub enum AutocompounderExecuteMsg {
    ...
    /// Join vault by depositing one or more funds
    Deposit { funds: Vec<OfferAsset> },
}
```

```ts
export interface AutocompounderInterface extends AutocompounderReadOnlyInterface {
...
  deposit: (
    {
      funds,
    }: {
      funds: AnsAsset[]
    },
    fee?: number | StdFee | 'auto',
    memo?: string,
    funds?: Coin[]
  ) => Promise<ExecuteResult>
...
}
  ```
  
I propose that we rename `fee`, `memo`, and `funds` to their underscored variants: `_fee`, `_memo`, and `_funds`.

**Comment by pyramation** [comment]
oh interesting! totally good idea

we can put it under a flag called `underscoreMetaParams` or something that makes sense
